### ISSUE TITLE
Getting started with Flutter

### ISSUE THREAD

**Issue by Hridyanshu** [USoC2020/Know_your_neighbourhood_a_better_way#8]
Instructions:

1. Install Android Studio in your systems
2. Create a sample project using flutter in it 
3. Take a Screenshot of the whole window 
4. Add it in Screenshots folder of the main repository [Your_Github_name.png]
5. create a PR

**Comment by Maulikchhabra** [comment]
I want to work on it.

**Comment by anushkabansal4** [comment]
I want to work on this issue.😊

**Comment by Hridyanshu** [comment]
> I want to work on this issue.😊

Go ahead and generate a PR :)
